### ISSUE TITLE
The Home page should be a tutorial

### ISSUE THREAD

**Issue by andreirtaylor** [andreirtaylor/MoneyTracker#15]
It is very difficult to see how to use the application when you first hit the home page. We should update the homepage to be a tutorial on how to use the application.

**Comment by jboretsky** [comment]
this was fixed in b056dd136f762eaf21aafe4936e3409b65f2913e

**Comment by andreirtaylor** [comment]
I think you forgot to add in the images.

**Comment by jboretsky** [comment]
fixed in b96b35885aa5242fa6c2afc9bd8cc9c56c36b403

**Comment by andreirtaylor** [comment]
Ok now its merged in.
