### ISSUE TITLE
Registration/Login does not perform enough sanitization

### ISSUE THREAD

**Issue by andreirtaylor** [andreirtaylor/MoneyTracker#16]
The login and registration pages need to perform more error checking before both registration and login. 

Specifially, when registering you can have users with the name "test" and "Test", you can have an email that is not vaild. Trailng white space is not trimmed. You can have an invaild email.

**Comment by andreirtaylor** [comment]
@adamtheschmidt some of these issue were fixed by #29 I believe. Can you give an update on this issue?

**Comment by adamtheschmidt** [comment]
most of these were fixed in #29 

the rest should be fixed in my next commit (5 minutes)

how is this different from issue https://github.com/andreirtaylor/BoardGameTracking/issues/22 ? if at all that is

**Comment by adamtheschmidt** [comment]
bug fixed in #30 , please close

**Comment by andreirtaylor** [comment]
great thanks.
